---
# playbooks/devops/install-docker.yml
- name: Installer Docker CE + Compose v2 (repo officiel)
  hosts: node01
  become: yes

  vars:
    # --- Utilisateurs à autoriser (groupe docker) ---
    docker_users: []           # ex: ['aziz','devops']

    # --- Options daemon.json (ex: cgroupdriver=systemd, logs) ---
    docker_daemon_options:
      log-driver: "json-file"
      log-opts:
        max-size: "10m"
        max-file: "3"
      exec-opts:
        - "native.cgroupdriver=systemd"

    # --- Paquets Docker officiels (laisser tel quel pour latest stable) ---
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

  pre_tasks:
    - name: Detect OS
      debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_os_family }})"

  tasks:
    ######################################################################
    # Debian / Ubuntu  — Patch complet (arch + signed-by + keyring)
    ######################################################################
    - name: (Debian/Ubuntu) Supprimer anciens paquets Docker si présents
      apt:
        name:
          - docker
          - docker.io
          - docker-engine
          - containerd
          - runc
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"
      tags: [docker, cleanup]

    - name: (Debian/Ubuntu) Paquets prérequis
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
      tags: [docker, prereqs]

    - name: (Debian/Ubuntu) Normaliser l’architecture APT
      set_fact:
        apt_arch: >-
          {{ 'amd64' if ansible_architecture in ['x86_64','amd64'] else
             'arm64' if ansible_architecture in ['aarch64','arm64'] else
             ansible_architecture }}
      when: ansible_os_family == "Debian"

    - name: (Debian/Ubuntu) Créer le répertoire de keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      when: ansible_os_family == "Debian"

    - name: (Debian/Ubuntu) Installer la clé GPG Docker dans /etc/apt/keyrings/docker.gpg
      shell: |
        set -e
        curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg
      when: ansible_os_family == "Debian"
      tags: [docker, repo]

    - name: (Debian/Ubuntu) Ajouter le dépôt Docker (signed-by + arch)
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        mode: '0644'
        content: |
          deb [arch={{ apt_arch }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} stable
      when: ansible_os_family == "Debian"
      tags: [docker, repo]

    - name: (Debian/Ubuntu) apt update
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: (Debian/Ubuntu) Installer Docker + plugins
      apt:
        name: "{{ docker_packages }}"
        state: present
      when: ansible_os_family == "Debian"
      tags: [docker, install]

    ######################################################################
    # RHEL / CentOS / Rocky / Alma
    ######################################################################
    - name: (RHEL-like) Supprimer anciens paquets Docker si présents
      package:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-engine
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine-selinux
          - containerd
          - runc
        state: absent
      when: ansible_os_family == "RedHat"
      tags: [docker, cleanup]

    - name: (RHEL-like) Prérequis
      package:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
      when: ansible_os_family == "RedHat"
      tags: [docker, prereqs]

    - name: (RHEL-like) Ajouter repo officiel Docker CE
      command: >
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo
      when: ansible_os_family == "RedHat"
      tags: [docker, repo]

    - name: (RHEL-like) Installer Docker + plugins
      package:
        name: "{{ docker_packages }}"
        state: present
      when: ansible_os_family == "RedHat"
      tags: [docker, install]

    ######################################################################
    # Configuration commune
    ######################################################################
    - name: Créer le groupe docker s'il n'existe pas
      group:
        name: docker
        state: present
      tags: [docker, users]

    - name: Ajouter les utilisateurs au groupe docker
      user:
        name: "{{ item }}"
        groups: docker
        append: yes
      loop: "{{ docker_users }}"
      when: docker_users | length > 0
      tags: [docker, users]

    - name: Créer /etc/docker
      file:
        path: /etc/docker
        state: directory
        owner: root
        group: root
        mode: '0755'
      tags: [docker, config]

    - name: Configurer /etc/docker/daemon.json
      copy:
        dest: /etc/docker/daemon.json
        mode: '0644'
        content: "{{ docker_daemon_options | to_nice_json }}"
      notify: Restart docker
      tags: [docker, config]

    - name: Activer et démarrer Docker
      service:
        name: docker
        state: started
        enabled: yes
      tags: [docker, service]

    - name: Vérifier versions (docker & compose)
      shell: |
        set -e
        docker --version
        docker compose version || true
      register: docker_versions
      changed_when: false
      tags: [docker, verify]

    - name: Afficher versions
      debug:
        var: docker_versions.stdout_lines
      tags: [docker, verify]

  handlers:
    - name: Restart docker
      service:
        name: docker
        state: restarted

